### ISSUE TITLE
Not working after installation, breaks other extensions 

### ISSUE THREAD

**Issue by Darkzarich** [donebd/vscode-keypromoter#47]
Installed this extension from https://marketplace.visualstudio.com/items?itemName=donebd.vscode-keypromoter and when I reload my vscode my typescript extension started to infinitely load. I cannot see any logs from this extension there is no such entry in output tab's select. Everything seems to work like before as soon as I turn this extension off.

OS: Ubuntu 22.04.3 LTS
Visual Studio Code version: 1.84.2

If you need any more info tell me please.

**Comment by donebd** [comment]
Which typescript extension is broken?

**Comment by Darkzarich** [comment]
Oh I think it wasn't an extension that broke

This thing broke: 

![image](https://github.com/donebd/vscode-keypromoter/assets/18618206/0849d80e-440e-4e03-bed1-7b71726db8ef)

After installing the extension it now never finishes initializing it 

I will rename the issue to reflect what actually happens

**Comment by Slava0135** [comment]
I am not able to reproduce this.

Maybe it is project specific - try load different one.
Or the extension just doesn't work with WSL.

**Comment by Darkzarich** [comment]
> Can you additionally reload window and send logs of extension if it exists, please? ![изображение](https://user-images.githubusercontent.com/55058233/284659734-effd53c9-dccc-4f14-94bd-06c92ac16598.png)

I tried and there is just no "Key Promoter" in the select you mentioned 

Tried with Windows version of vscode and everything appears to be just fine: seeing both Key Promoter in the output and messages from your screenshot.

It appears the problem is related to WSL. Even though my WSL is just Ubuntu 22.04.3 but maybe some important libs are missing in order for this extension to work. 

Maybe someone with pure non-WSL Ubuntu could confirm if it works for them.

**Comment by donebd** [comment]
I have Ubuntu as main OS. This behaviour is not reproducing. I will try same situation with WSL

**Comment by donebd** [comment]
Which OS you use as remote client, Windows?

**Comment by Darkzarich** [comment]
Windows 10 with WSL 2 with Ubuntu 22.04.3 installed

**Comment by meskill** [comment]
I'm also having an issue with the extension on WSL2. It just doesn't work in wsl.

I found the error log why it's not starting:

```
2024-01-01 10:03:45.197 [error] Activating extension donebd.vscode-keypromoter failed due to an error:
2024-01-01 10:03:45.198 [error] Error: libX11.so.6: cannot open shared object file: No such file or directory
	at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at c._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at load (/home/nixos/.vscode-server/extensions/donebd.vscode-keypromoter-1.0.2/node_modules/node-gyp-build/node-gyp-build.js:22:10)
	at Object.<anonymous> (/home/nixos/.vscode-server/extensions/donebd.vscode-keypromoter-1.0.2/node_modules/uiohook-napi/dist/index.js:6:38)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at c._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Object.<anonymous> (/home/nixos/.vscode-server/extensions/donebd.vscode-keypromoter-1.0.2/out/keylogger/keyLogger.js:4:24)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at c._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Object.<anonymous> (/home/nixos/.vscode-server/extensions/donebd.vscode-keypromoter-1.0.2/out/extension.js:33:21)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at c._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/loader.js:5:98)
	at f.vb (/home/nixos/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/workbench/api/node/extensionHostProcess.js:168:30730)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	```
